repos:

  # ruff: python code formatter and linter, this replaces black and isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # sqlfluff: sql formatter and linter
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix

  # jupytext: enables conversion between notebooks and python scripts
  - repo: https://github.com/mwouts/jupytext
    rev: v1.17.0
    hooks:
    - id: jupytext
      args: [--from, ipynb, --to, "py:percent", --pipe, black, --pipe, "isort - --profile black"]
      stages:
        - commit
      additional_dependencies:
        - jupytext
        - black
        - isort

  # pre-commit-hooks: a collection of pre-commit hooks to enforce repository hygiene
  # list of supported hooks: https://pre-commit.com/hooks.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 5.0.0
    hooks:
      - id: trailing-whitespace # remove trailing whitespace
      - id: end-of-file-fixer # fix end of file
      - id: check-added-large-files # check for large files
        args: [ "--maxkb=500" ]
      - id: check-merge-conflict # check for merge conflicts
      - id: detect-private-key # check for private keys
      - id: check-merge-conflict # check for merge conflicts
      - id: check-yaml # check for yaml errors
        args: [ "--allow-multiple-documents" ]
      - id: mixed-line-ending # check for mixed line endings
        args: [ "--fix=lf" ]