name: analytics-repo

volumes:
  dagster-data:
  venv-data:

services:
  dagster:
    build: .
    image: dafrose/analytics-repo
    restart: unless-stopped
    command:
      - >
        set -e &&
        cd /app &&
        uv pip install --system . &&
        uv sync &&
        dagster dev -h 0.0.0.0 -p 3030;
    init: true
    environment:
      PYTHON_ENV: development
      DAGSTER_HOME: /app
      GCP_APPLICATION_CREDENTIALS: /app/gcp_credentials.json
      GCP_ACCESS_KEY: ${GCP_ACCESS_KEY}
      GCP_BUCKET: ${GCP_BUCKET}
      GCP_ENDPOINT: ${GCP_ENDPOINT}
      GCP_REGION: ${GCP_REGION}
    volumes:
      - .:/app
      - venv-data:/app/.venv
      - ./gcp_credentials.json:/app/gcp_credentials.json:ro
    ports:
      - "3030:3030"
    depends_on:
      dagster-db:
        condition: service_healthy

  dagster-db:
    image: bitnami/postgresql:16.4.0-debian-12-r8
    restart: unless-stopped
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: dagster
    volumes:
      - dagster-data:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "dagster" ]
      start_period: 5s
      interval: 20s
      retries: 3
      timeout: 2s
